- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      # Python Dev
      - python-dev
      - python-setuptools
      - python-virtualenv

      # Dep
      - libenchant1c2a

      # others
      - vim
      - build-essential

      # Data
      - libxslt-dev



- name: Install SciPi Dependencies
  sudo: yes
  apt: pkg=python-scipy state=build-dep

- name: Upgrade pip
  sudo: yes
  shell: pip install --upgrade pip

- name: Setup Base Virtualenv
  sudo: yes
  pip: requirements={{ virtualenv_path }}requirements.txt

- name: Setup Additonal Python requirements
  sudo: yes
  pip: requirements={{ virtualenv_path }}additonal-requirements.txt

- name: Install nltk corpus
  sudo: yes
  command: python -m nltk.downloader -d /usr/local/share/nltk_data all
